### ISSUE TITLE
Using the deathmessages 1.17.1 error:

### ISSUE THREAD

**Issue by thiagogebrimm** [HMJosh/DiscordBotAPI#1]
```
[02:04:39 ERROR]: Could not pass event BroadcastDeathMessageEvent to DeathMessages v1.3.8
java.lang.LinkageError: loader constraint violation: loader org.bukkit.plugin.java.PluginClassLoader @5ba40539 wants to load interface net.dv8tion.jda.api.JDA. A different interface with the same name was previously loaded by org.bukkit.plugin.java.PluginClassLoader @56a80f46. (net.dv8tion.jda.api.JDA is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @56a80f46, parent loader 'app')
        at net.joshb.deathmessages.hook.DiscordBotAPIExtension.sendDiscordMessage(DiscordBotAPIExtension.java:40) ~[?:?]
        at net.joshb.deathmessages.listener.customlisteners.BroadcastPlayerDeathListener.normal(BroadcastPlayerDeathListener.java:107) ~[?:?]
        at net.joshb.deathmessages.listener.customlisteners.BroadcastPlayerDeathListener.broadcastListener(BroadcastPlayerDeathListener.java:72) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor479.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1292]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1292]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1292]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Purpur-1292]
        at net.joshb.deathmessages.listener.EntityDeath.onEntityDeath(EntityDeath.java:83) ~[?:?]
        at net.joshb.deathmessages.listener.EntityDeath.onEntityDeath_HIGH(EntityDeath.java:180) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor486.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1292]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1292]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1292]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Purpur-1292]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:893) ~[patched_1.17.1.jar:git-Purpur-1292]
        at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:846) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:116) ~[patched_1.17.1.jar:git-Purpur-1292]
        at com.earth2me.essentials.commands.Commandkill.updatePlayer(Commandkill.java:40) ~[?:?]
        at com.earth2me.essentials.commands.EssentialsLoopCommand.lambda$loopOnlinePlayers$1(EssentialsLoopCommand.java:67) ~[?:?]
        at com.earth2me.essentials.commands.EssentialsLoopCommand.loopOnlinePlayersConsumer(EssentialsLoopCommand.java:110) ~[?:?]
        at com.earth2me.essentials.commands.EssentialsLoopCommand.loopOnlinePlayers(EssentialsLoopCommand.java:67) ~[?:?]
        at com.earth2me.essentials.commands.Commandkill.run(Commandkill.java:25) ~[?:?]
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:168) ~[?:?]
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:163) ~[?:?]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:764) ~[?:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:667) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Purpur-1292]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.17.1.jar:git-Purpur-1292]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:830) ~[patched_1.17.1.jar:git-Purpur-1292]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2309) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2120) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2101) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-1292]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1422) ~[patched_1.17.1.jar:git-Purpur-1292]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Purpur-1292]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1400) ~[patched_1.17.1.jar:git-Purpur-1292]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1393) ~[patched_1.17.1.jar:git-Purpur-1292]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1369) ~[patched_1.17.1.jar:git-Purpur-1292]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1280) ~[patched_1.17.1.jar:git-Purpur-1292]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1292]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by thiagogebrimm** [comment]
Looks like it's incompatibility with Spicord plugin, it would be nice to add that compatibility.

**Comment by HMJosh** [comment]
Join https://discord.gg/K9zVDwt I dont look at this often
